### ISSUE TITLE
Executing 'python -m monitor_rtl433' fails

### ISSUE THREAD

**Issue by mrock99** [mcbridejc/monitor_rtl433#1]
I'm new to python so this is may very well be me doing something wrong...
I'm trying to run monitor_rtl433 on windows. I have 'prometheus.exe --config.file prometheus.yml --web.listen-address ":9090" --storage.tsdb.path "data"' running on the same windows machine and have rtl_433 installed and working on the same machine also.
When I try to execute 'python -m monitor_rtl433' in a command window I get an error report:
--------------------------------
'"rtl_433 -F json"' is not recognized as an internal or external command,
operable program or batch file.
Exception in thread Thread-1 (rx_thread_entry):
Traceback (most recent call last):
  File "C:\Users\v_war\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\v_war\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\v_war\AppData\Local\Programs\Python\Python311\Lib\site-packages\monitor_rtl433-1.0-py3.11.egg\monitor_rtl433\run.py", line 26, in rx_thread_entry
    message = receiver.get_message()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v_war\AppData\Local\Programs\Python\Python311\Lib\site-packages\monitor_rtl433-1.0-py3.11.egg\monitor_rtl433\rtl433.py", line 23, in get_message
    return json.loads(outs)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\v_war\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v_war\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\v_war\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
 ----------------------
 
I can run 'rtl_433 -F json' in the same command window without a problem. It is in my path so I don't know why an error occurs when executing 'python -m monitor_rtl433'.

Any help would be appreciated.

Thanks,

**Comment by rhermsen** [comment]
@mrock99
I'm not using the RTL433 part, but based on the first error the rtl_433 executable cannot be found.
See:
https://github.com/mcbridejc/monitor_rtl433/blob/c04494b759371ae96a1bdf65848f92b203bec076/monitor_rtl433/run.py#L20
Which calls the following, where the rtl_433 executable is executed:
https://github.com/mcbridejc/monitor_rtl433/blob/c04494b759371ae96a1bdf65848f92b203bec076/monitor_rtl433/rtl433.py#L9
Maybe you can add the rtl_433 in the %PATH% or execute it with an absolute path.

Hope this helps...
